version: '3.5'

services:

  # We need the NATS really:
  #  - as the discovery service;
  #  - as the message broker service;
  #  - as the transport method (optional);
  nats:
    image: nats:2.0.0
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    command:
      - "-DV"
    networks:
      - go-micro-boilerplate-docker
    restart: always

  #--------------------------------------------------------------------------#
  # SERVICES DEFINITIONS
  #--------------------------------------------------------------------------#

  # account-svc configures account-svc to run it locally.
  account-svc:
    build:
      context: .
      dockerfile: ./services/account-svc/Dockerfile
    depends_on:
      - nats
    environment:
      # This is the indicator that the service is running locally.
      DOCKER_COMPOSE: "true"
      # Define registry type and its address.
      MICRO_REGISTRY: nats
      MICRO_REGISTRY_ADDRESS: nats:4222
      # Define transport type.
      MICRO_TRANSPORT: nats
      MICRO_TRANSPORT_ADDRESS: nats:4222
      # Define message broker type and its address.
      MICRO_BROKER: nats
      MICRO_BROKER_ADDRESS: nats:4222
    networks:
      - go-micro-boilerplate-docker
    restart: always

networks:
  go-micro-boilerplate-docker:
    driver: bridge
    name: go-micro-boilerplate-docker
